#!/bin/sh	

until timeout 10s celery -A celery_factory:celery inspect ping; do	
    >&2 echo "Celery workers not available"	
done	

echo 'Starting flower'	
celery -A celery_factory:celery flower --loglevel=info -E
